@api = http://localhost:3000/api


GET {{api}}/sucursales?ordenar=asc HTTP/1.1

###

GET {{api}}/sucursales/NOMBRE_SUCURSALES HTTP/1.1
Content-Type: application/json

{
    "NOMBRE_SUCURSALES": "Unicenter"
}

###

POST {{api}}/sucursales HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "NOMBRE_SUCURSAL": "PRUEBA",
    "HORARIOS": "19:00",
    "ASIENTOS": "A1"
}

###

DELETE {{api}}/sucursales/7204 HTTP/1.1

###

PUT {{api}}/sucursales/7203 HTTP/1.1
Content-Type: application/json

{
    "id": 7203,
    "NOMBRE_SUCURSAL": "PROBANDOO",
    "HORARIOS": "15:00",
    "ASIENTOS": "B3"
}

###

PATCH {{api}}/sucursales/7204 HTTP/1.1
Content-Type: application/json

{
    "id": 7204,
    "NOMBRE_SUCURSAL": "Mendoza"
}