@api = http://localhost:3000/api

# Obtener todos los horarios ordenados de forma ascendente (A-Z)
GET {{api}}/horarios?ordenar=asc HTTP/1.1

###

# Obtener todos los horarios ordenados de forma descendente (Z-A)
GET {{api}}/horarios?ordenar=desc HTTP/1.1

###

# Obtener los datos de un horario específico por su nombre
GET {{api}}/horarios HTTP/1.1
Content-Type: application/json

###

# Obtener detalle completo con sucursal de un horario
GET http://localhost:3000/api/horarios/detalle/16:00 HTTP/1.1
Content-Type: application/json

###

# Crear un nuevo horario
POST {{api}}/horarios HTTP/1.1
Content-Type: application/json

{
  "SUCURSAL_ID": 1,
  "HORA": "17:00"
}


###

# Eliminar un horario por ID
DELETE http://localhost:3000/api/horarios/2 HTTP/1.1


###

# Actualizar el horario de una sucursal existente por ID
PUT {{api}}/horarios/3 HTTP/1.1
Content-Type: application/json

{
    "SUCURSAL_ID": 3,
    "HORA": "11:00"
}

###

PATCH {{api}}/horarios/4 HTTP/1.1
Content-Type: application/json

{
    "HORA": "23:00"
}