module.exports = {
    getSucursales:`USE CINEMALAND;
        SELECT DISTINCT NOMBRE_SUCURSAL FROM SUCURSALES;`,


    addSucursal:`USE CINEMALAND INSERT INTO SUCURSALES
    (NOMBRE_SUCURSAL,
    HORARIOS,
    ASIENTOS) 
    VALUES (
    @NOMBRE_SUCURSAL,
    @HORARIOS,
    @ASIENTOS);`,



    getSucursalById: `USE CINEMALAND SELECT * FROM NOMBRE_SUCURSAL WHERE ID = @ID`,

    deleteSucursal:`USE CINEMALAND DELETE FROM NOMBRE_SUCURSAL WHERE ID = @ID`

}